### ISSUE TITLE
Bug: TypeError: DockerDetector.__init__() got an unexpected keyword argument 'default_port'

### ISSUE THREAD

**Issue by ErikKalkoken** [Maxteabag/sqlit#60]
After upgrading to 1.2 starting sqlit aborts with the following error:

```
Traceback (most recent call last):
  File "/home/erik/.local/bin/sqlit", line 7, in <module>
    sys.exit(main())
  File "/home/erik/.local/share/pipx/venvs/sqlit-tui/lib/python3.10/site-packages/sqlit/cli.py", line 408, in main
    for db_type in get_supported_db_types():
  File "/home/erik/.local/share/pipx/venvs/sqlit-tui/lib/python3.10/site-packages/sqlit/domains/connections/providers/catalog.py", line 50, in get_supported_db_types
    _ensure_discovered()
  File "/home/erik/.local/share/pipx/venvs/sqlit-tui/lib/python3.10/site-packages/sqlit/domains/connections/providers/catalog.py", line 46, in _ensure_discovered
    _discover_providers()
  File "/home/erik/.local/share/pipx/venvs/sqlit-tui/lib/python3.10/site-packages/sqlit/domains/connections/providers/catalog.py", line 40, in _discover_providers
    import_module(f"{__package__}.{name}.provider")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/erik/.local/share/pipx/venvs/sqlit-tui/lib/python3.10/site-packages/sqlit/domains/connections/providers/flight/__init__.py", line 3, in <module>
    from sqlit.domains.connections.providers.flight.provider import SPEC
  File "/home/erik/.local/share/pipx/venvs/sqlit-tui/lib/python3.10/site-packages/sqlit/domains/connections/providers/flight/provider.py", line 28, in <module>
    docker_detector=DockerDetector(
TypeError: DockerDetector.__init__() got an unexpected keyword argument 'default_port'
```

**Comment by Maxteabag** [comment]
Thanks for reporting!

**Comment by ErikKalkoken** [comment]
I just upgrade to 1.2.0.1 and now it works. I have also upgraded pipx to Python 3.13 (from 3.10), so not sure which of two changes fixed it.
